### ISSUE TITLE
Can't select events with magnitudes smaller 1.0

### ISSUE THREAD

**Issue by KDFischer** [INGV/qquake#18]
When loading events using the tab "search by parameters" the minimum magnitude can not be set to values smaller than 1.0. I'm working with mining induced events and many of the events in my database are even smaller than 0.0!

**Comment by MarioLocati** [comment]
Could you please explain why is not possible to solve your problem by forcing a maximum magnitude of 1 and leave unchecked the minimum magnitude? (see picture)

As far as I understand, if you leave out the "minmag" parameter the FDSN-event service should provide you all the events below magnitude 1, without applying any threshold to lower magnitude events. In this way, even events having negative magnitudes should be preserved in the output, isn't that the case?

I might missing some information here, could you please elaborate a bit more?

![image](https://user-images.githubusercontent.com/20398568/113156659-7b572800-923a-11eb-93d4-990cd0d2434b.png)

**Comment by KDFischer** [comment]
Hi Mario,
thank you for your quick answer. If I do not check 'Min' in the Magnitude field I do indeed get all events smaller than the max magnitude. In my case the very small magnitudes are not very well constrained. Therefore I wanted to set the min magnitude to e.g. 0.5 which did not work. The same is true for the max magnitude which can not be set below 1.0.

As a work-around I could filter the events within QGIS, but the query without a min magnitude already returns a large list and the qquake is issuing a warning (but is working as expected).

Cheers,
Kasper

**Comment by MarioLocati** [comment]
So, your suggestion is to lower the minimum magnitude to a negative number?
I am not used to negative magnitude events, which could be the meaningful lowest value we should put in QQuake?
Fixing the lowest possible magnitude to -1 would be correct in your experience?

**Comment by KDFischer** [comment]
From a mathematical and geophysical point of view there is no minimum magnitude. I looked at the code of qquake and tried to fix it my self. From the description of the QdoubleSpinBox it seems not possible not to limit the minimum value to enter. Therefore I search in seismological research papers to find a lower limit. Within the JAGUARS project (https://www.gfz-potsdam.de/en/section/geomechanics-and-rheology/projects/microseismicity-and-acoustic-emission-in-deep-gold-mine-in-south-africa-jaguars/) events of magnitude -5 could be observed in deep gold mines. I also notice that some people are using -9 as a magnitude when it is not determined. So maybe the limit could be at -8 ?

I can create a pull request or send a patch if you like.

**Comment by MarioLocati** [comment]
No need to send a patch.
Prior to adopt this solution, let me investigate a bit more the matter with other colleagues in my organization, OK?

**Comment by KDFischer** [comment]
No problem. I have forked the code and fixed it locally.

**Comment by MarioLocati** [comment]
I have introduced the filtering for negative magnitudes in the main branch, see 29a6d766fbaf58e485f2077aaf31b8eea67657a7
Can we consider this issue closed?

**Comment by KDFischer** [comment]
Thank you very much. This solves the issue.
