### ISSUE TITLE
Earthquake depth

### ISSUE THREAD

**Issue by ghtmtt** [INGV/qquake#4]
Here the mockup before the explanation:

![image](https://user-images.githubusercontent.com/2884884/100846514-e8ba9e00-347e-11eb-8112-0786472b3095.png)

If the data are downloaded as plain `txŧ` the depth values are in km so if the user choose `meters` in the UI we should multiply and change the label accordingly.

More *tricky* is the `Values` choice. If the earthquake is below the sea level then the values should remain positive while if the earthquake is above the sea level they should remain negative.

cc @MarioLocati (for a more detailed and human friendly explanation)

cc @nyalldawson

**Comment by MarioLocati** [comment]
Seismological services delivers positive sign depth values when the hypocentre of the earthquake is below the sea level, and negative values when the hypocentre is above the sea level. This is valid both for the FDSN-event and for the macroseismic service currently implemented in QQuake, and valid when retrieving data using the text output or the QuakeML output.<br>
The `Values` drop down button should allow users to select whether to get the depth values like that (positive when below the sea level) or reverse it (negative when below the sea level).<br>
The two down labels contained in the `Values` buttons should be :
- positive values when below the sea level, negative when above the sea level
- negative values when below the sea level, positive when above the sea level
