### ISSUE TITLE
https://webservices.ingv.it/fdsnws/event/1/application.wadl error in minlongitude

### ISSUE THREAD

**Issue by nyalldawson** [INGV/qquake#40]
@MarioLocati not related to the plugin, but the https://webservices.ingv.it/fdsnws/event/1/application.wadl response incorrectly lists "minlongitude" twice, when one of these should be "maxlongitude":

```
				<param name="minlongitude" style="query" type="xs:double" default="-180"/>
				<param name="minlongitude" style="query" type="xs:double" default="180"/>
```

Perhaps you have contacts you could approach to fix this?

**Comment by MarioLocati** [comment]
@vlauciani I think this one if for you

**Comment by vlauciani** [comment]
yes! I'll fix it this afternoon!

**Comment by vlauciani** [comment]
Hi all

The fix was very easy... 
In the version `1.1.52.6` the problem was solved!

Valentino.
