### ISSUE TITLE
Different list of OGC layers in the filter windows

### ISSUE THREAD

**Issue by MarioLocati** [INGV/qquake#43]
The list of layers that appears in the pop-down menu in the CQL filtering window must list the very same layers showed in the main windows.
Currently, it seems to me that the pop-down menu list all layers published by the OGC endpoint instead.

![image](https://user-images.githubusercontent.com/20398568/144990166-fda73be3-bada-49ab-990c-ce7221266765.png)

![image](https://user-images.githubusercontent.com/20398568/144990246-362c42de-c491-4950-b424-e1fa0796fbec.png)

**Comment by nyalldawson** [comment]
I couldn't find anyway to restrict the layers to a specific set. We can specify the typename parameter if just one layer is selected, but I couldn't find anyway to specify more then one typename at a time.

**Comment by MarioLocati** [comment]
Well, the list of layers that shoul appear in the list are listed in the tag "layers" in the main configuration file, for example the layers that should appear for the OGC WMS "AHEAD-EPICA" is https://github.com/INGV/qquake/blob/master/qquake/config/config.json#L1952

**Comment by nyalldawson** [comment]
That's not a problem -- the problem is that wfs doesn't support specifying multiple layers when retrieving the fields. (I guess we could always request them all and then filter the combo box entries though!)

I guess my bigger question is how useful it is to specify one query when multiple layers will be loaded anyway? How often will the one query work across different layers?

**Comment by MarioLocati** [comment]
Yes, definitely, we should request all available layers and then filter the combo box entries based on what is reported in the config.json

The layer selector is precisely meant for specifying query to a specific layer among those available for that specific service.
When a service provides multiple layers, the user may want to submit a specific query to one or more specific layers, the query is not meant to work across all layers, it will never work that way.
