### ISSUE TITLE
"Load web service capabilities" lead to a Python error

### ISSUE THREAD

**Issue by MarioLocati** [INGV/qquake#48]
I tested the new feature allowing the user to retrieve FDSN-event capabilities from the application.wadl when creating a new service.

As a first attempt I have used the endpoint "http://earthquake.usgs.gov/fdsnws/event/1/" and after pressing the button "Load web service capabilities" I get the following Python error

> WARNING    Traceback (most recent call last):
>  File "C:\Users/mario/AppData/Roaming/QGIS/QGIS3\profiles\x/python/plugins\qquake\gui\service_configuration_widget.py", line 390, in response_finished
>  self._set_state_from_wadl(WadlServiceParser.parse_wadl(content, self.service_type, url))
>  File "C:\Users/mario/AppData/Roaming/QGIS/QGIS3\profiles\x/python/plugins\qquake\services\wadl.py", line 55, in parse_wadl
>  assert resources_elements.length() == 1
> AssertionError

Using the endpoint "https://www.emidius.mi.ingv.it/fdsnws/event/1/" lead to the very same Python error.

I then tried using the endopoint "https://www.seismicportal.eu/fdsnws/event/1/" and after pressing the button "Load web service capabilities" I did not get any error but strangely it lead to a changed "Web service URL" to "http://www.seismicportal.eu/fdsnws/event/1/counts?" leaving me quite puzzled.

**Comment by nyalldawson** [comment]
> I then tried using the endopoint "https://www.seismicportal.eu/fdsnws/event/1/" and after pressing the button "Load web service capabilities"

What's the correct application.wadl url for this service? http://www.emidius.mi.ingv.it/fdsnws/event/1/application.wadl gives me an error

**Comment by MarioLocati** [comment]
The URL wan not correct, it is not http://www.emidius.mi.ingv.it/fdsnws/event/1/application.wadl, it is http://emidius.mi.ingv.it/fdsnws/event/1/application.wadl
