### ISSUE TITLE
is it possible to add the time parameter in the earthquake selection?

### ISSUE THREAD

**Issue by EzioDAlema** [INGV/qquake#60]
It is currently possible to select earthquakes by entering only the initial and final data. Is it also possible to insert the time parameter in the Time Coverage - Start arm?
for example from 2021-05-15 00:00:00 to 2021-05-15 15:30:00?

**Comment by MarioLocati** [comment]
I have implemented the time parameter for fdsn based services.
@EzioDAlema can you please confirm that all is working as expected?

**Comment by EzioDAlema** [comment]
Hi @MarioLocati , I can confirm that by selecting the time parameter, the query works correctly.
For example, if I select the earthquakes from 2023-09-03 10:00 utc to 2023-09-03 15:00 utc, there are 3 events, consistent with what is reported on the INGV websites.
Thank you
