### ISSUE TITLE
Split config.json

### ISSUE THREAD

**Issue by robertovallone** [INGV/qquake#62]
config.json should be split into several JSON files: i.e., different files for different kinds of services or service providers

**Comment by MarioLocati** [comment]
I have splitted the configuration with the following commits
https://github.com/INGV/qquake/commit/624745e1deae37ae26f1b991201ab601ed85d119
https://github.com/INGV/qquake/commit/916146c02dc6335e5a37b26048a2d796b6502b71
https://github.com/INGV/qquake/commit/ca32f30ebc2c1d2acd113b9bbc5afe1c2b7ba62a
https://github.com/INGV/qquake/commit/92cdc9b92ac64a4794951d99e53792b1d6b6fd1c
https://github.com/INGV/qquake/commit/ef527782ba0f24384d1ca30150e179e890703d03

@robertovallone Please, download a snapshot of the plugin, try it out and let me know if everything is working as expected, cheers.

**Comment by robertovallone** [comment]
I can confirm it works great on my QGis 3.22.4-Białowieża (Linux)
