### ISSUE TITLE
Search by Identifiers - Macroseismic Service

### ISSUE THREAD

**Issue by AndreaAntonucci** [INGV/qquake#64]
The epicenter of the selected event does not show up in the map using the "Extended output table" selecting "Search by Identifiers" in the "Macroseismic data" service.
The problem is related to the simbology because the corresponding value used to plot the epicenter is not the same to the header of the coloumn.

**Comment by MarioLocati** [comment]
Issue was solved while solving https://github.com/INGV/qquake/issues/71
