### ISSUE TITLE
WFS service does not allow fetching only selected layers

### ISSUE THREAD

**Issue by robertovallone** [INGV/qquake#65]
In WFS, available layers are correctly shown for every source with a checkmark alongside to select layers to load. But all layers are loaded anyway, whichever are the selected ones.

**Comment by MarioLocati** [comment]
Solved with https://github.com/INGV/qquake/commit/3939f1b7c6ebd3993d042472ca904573444d38d3#diff-a36a1fb75e4be5df620829e84703f3d7c544042a0d4a3d9e27cb40af0f835c8f
